import asyncio
from services.tts_service import text_to_speech
from config import settings

async def main():
    print(f"API Key available: {bool(settings.sarvam_api_key)}")
    try:
        res = await text_to_speech("Pradhan Mantri kisan samman nidhi", "hi-IN")
        print("Generated bytes:", len(res))
    except Exception as e:
        print("Exception:", str(e))

if __name__ == "__main__":
    asyncio.run(main())
