"""
db/query_log.py — ORM Model for Query Logging
-----------------------------------------------
Every query processed by the backend gets logged here (anonymously).
No personal data is stored — only query text, intent, scheme, and timing.
"""
from datetime import datetime
from sqlalchemy import String, Float, Boolean, Integer, DateTime, Text
from sqlalchemy.orm import Mapped, mapped_column
from database import Base


class QueryLog(Base):
    """
    Maps to the `query_logs` table in PostgreSQL.
    SQLAlchemy ORM = Python class that represents a database table.
    """
    __tablename__ = "query_logs"

    # Primary key (auto-incrementing integer)
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)

    # Anonymous session ID (UUID generated by frontend, no user data)
    session_id: Mapped[str | None] = mapped_column(String(36), nullable=True)

    # The user's actual question
    query_text: Mapped[str] = mapped_column(Text, nullable=False)

    # Language the user chose
    language: Mapped[str | None] = mapped_column(String(10), nullable=True)

    # What intent was detected (OVERVIEW, ELIGIBILITY, etc.)
    intent: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # Which scheme was matched
    scheme_id: Mapped[str | None] = mapped_column(String(20), nullable=True)

    # How confident was the scheme match (0.0 to 1.0)
    confidence: Mapped[float | None] = mapped_column(Float, nullable=True)

    # Did we call Gemini API for this query?
    gemini_used: Mapped[bool] = mapped_column(Boolean, default=False)

    # How long did the request take (milliseconds)?
    response_time_ms: Mapped[int | None] = mapped_column(Integer, nullable=True)

    # When was the query made
    created_at: Mapped[datetime] = mapped_column(
        DateTime, default=datetime.utcnow, nullable=False
    )

    def __repr__(self) -> str:
        return f"<QueryLog id={self.id} scheme={self.scheme_id} conf={self.confidence}>"
